name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 1: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 3: Build Docker image
    - name: Build Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 -t gitops:latest .

    # Step 4: Tag Docker image
    - name: Tag Docker image
      run: docker tag gitops:latest skylyt/gitops:latest

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push skylyt/gitops:latest
